### ISSUE TITLE
Add-on Details

### ISSUE THREAD

**Issue by Cyber5imon** [irvinm/TST-Lock#13]
The details section for this add-on references `Discussion: https://github.com/piroor/treestyletab/issues/2104`

It should probably be changed to reference this repository directly.

**Comment by irvinm** [comment]
I assume you mean https://github.com/irvinm/TST-Lock in the readme.md?

I just wanted to give a "historical" perspective of how and why this addon came into existence.  I added a direct link to the "issues" section to report any defects or enhancement requests.  Thanks.
